export const Audios : any = {
    "ES": {
      "Red": require('../../assets/ES/red.aac'),
      "Blue": require('../../assets/ES/blue.aac'),
      "Yellow": require('../../assets/ES/yellow.aac'),
      "Purple": require('../../assets/ES/purple.aac'),
      "Green": require('../../assets/ES/green.aac'),
      "Monkey": require('../../assets/ES/monkey.aac'),
      "Cow": require('../../assets/ES/cow.aac'),
      "Lion": require('../../assets/ES/lion.aac'),
      "Cat": require('../../assets/ES/cat.aac'),
      "Dog": require('../../assets/ES/dog.aac'),
      "One": require('../../assets/ES/one.aac'),
      "Two": require('../../assets/ES/two.aac'),
      "Three": require('../../assets/ES/three.aac'),
      "Four": require('../../assets/ES/four.aac'),
      "Five": require('../../assets/ES/five.aac'),
    },
    "EN": {
        "Red": require('../../assets/EN/red.aac'),
        "Blue": require('../../assets/EN/blue.aac'),
        "Yellow": require('../../assets/EN/yellow.aac'),
        "Purple": require('../../assets/EN/purple.aac'),
        "Green": require('../../assets/EN/green.aac'),
        "Monkey": require('../../assets/EN/monkey.aac'),
        "Cow": require('../../assets/EN/cow.aac'),
        "Lion": require('../../assets/EN/lion.aac'),
        "Cat": require('../../assets/EN/cat.aac'),
        "Dog": require('../../assets/EN/dog.aac'),
        "One": require('../../assets/EN/one.aac'),
        "Two": require('../../assets/EN/two.aac'),
        "Three": require('../../assets/EN/three.aac'),
        "Four": require('../../assets/EN/four.aac'),
        "Five": require('../../assets/EN/five.aac'),
    },
    "POR": {
        "Red": require('../../assets/POR/red.aac'),
        "Blue": require('../../assets/POR/blue.aac'),
        "Yellow": require('../../assets/POR/yellow.aac'),
        "Purple": require('../../assets/POR/purple.aac'),
        "Green": require('../../assets/POR/green.aac'),
        "Monkey": require('../../assets/POR/monkey.aac'),
        "Cow": require('../../assets/POR/cow.aac'),
        "Lion": require('../../assets/POR/lion.aac'),
        "Cat": require('../../assets/POR/cat.aac'),
        "Dog": require('../../assets/POR/dog.aac'),
        "One": require('../../assets/POR/one.aac'),
        "Two": require('../../assets/POR/two.aac'),
        "Three": require('../../assets/POR/three.aac'),
        "Four": require('../../assets/POR/four.aac'),
        "Five": require('../../assets/POR/five.aac'),
    }
};